function [Jx, Ju] = stateFcnJacobian(x, u)
% This function was generated by Model Predictive Control Toolbox (Version 8.1).
% 14-Jul-2023 10:09:04
%# codegen
persistent ADdata
if isempty(ADdata)
    ADdata = coder.load('stateFcnJacobianADdata','constants');
end
[~,J] = stateFcnJacobianAD([x;u],ADdata.constants);
Jx = J(:,1:1);
Ju = J(:,3);
